= Introduction

This section introduces the Jakarta Config Specification. Unless noted otherwise, this section is non-normative.

CAUTION: You are reading an incomplete DRAFT specification.  The following is subject to change.

== Overview

The Jakarta Config Specification defines Java APIs and their associated contracts that allow
xref:terminology.adoc#component-developer[Java component developers] and xref:terminology.adoc#implementor[product
vendors] to define xref:terminology.adoc#term-configuration-interface[configuration interfaces] and load
xref:terminology.adoc#configuration-object[configuration objects] representing their
xref:terminology.adoc#component[components'] and products' xref:terminology.adoc#term-configuration[configuration].

This specification addresses at least the following areas:

* How a xref:terminology.adoc#component-developer[Java developer] acquires a Java representation of her
  xref:terminology.adoc#component[component's] configuration (what a developer must do to use an implementation of this
  specification)

* How this specification's concept of xref:terminology.adoc#term-configuration[configuration] is represented in Java
  (what a xref:terminology.adoc#term-configuration-interface[configuration interface] looks like, and how a developer
  might define one)

* How a xref:terminology.adoc#configuration-object[configuration object] is xref:terminology.adoc#load[loaded] (what
  various xref:terminology.adoc#loader[loaders] must do)

* How xref:terminology.adoc#persistent-configuration[persistent configuration] is represented external to a component or
  application (what must be true of xref:terminology.adoc#configuration-format[configuration formats])

* How a xref:terminology.adoc#term-configuration-interface[configuration interface] designates or maps to a portion of
  persistent configuration
