= Loading

This section defines the operation of _xref:terminology.adoc#load[loading]_.  Loading is the operation of writing and
using Java code that acquires a xref:terminology.adoc#configuration-object[configuration object] from an implementation
of the Jakarta Config specification.

== Overview

A xref:terminology.adoc#component-developer[component developer] writes Java code that interacts with an implementation
of the Jakarta Config specification's `jakarta.config.Loader` interface to load a configuration object.  She supplies
the `Loader` with the Java objects that comprise a xref:terminology.adoc#load-request[load request].  The `Loader`
implementation responds by returning a xref:terminology.adoc#suitability[suitable]configuration object, or throwing a
`jakarta.config.NoSuchObject` exception to indicate its xref:terminology.adoc#absence[absence].

CAUTION: You are reading an incomplete DRAFT specification.  The following is subject to change.

== Actors and Roles

The actors and roles that take part in the operation of loading are:

. A xref:terminology.adoc#component-developer[component developer]. An actor playing this role writes Java code in a
xref:terminology.adoc#component[component] to interact with an implementation of the Jakarta Config specification's
`jakarta.config.Loader` interface.

. An xref:terminology.adoc#application-assembler[application assembler]. An actor playing this role packages
xref:terminology.adoc#component[components] and zero or more xref:terminology.adoc#configuration[configuration]s in
particular xref:terminology.adoc#configuration-format[formats] for one or more
xref:terminology.adoc#environment[environments].

. An xref:terminology.adoc#implementor[implementor]. An actor playing this role provides an implementation of the
Jakarta Config specification, and hence also an implementation of the `jakarta.config.Loader` interface.

