= Property Expression

The property expression is in the format of ${a.property}. When resoving the property expression, the value of `a.property` will be used.
With the property expression, it enables a property refer to another property.

== An example

Consider the following example:

[source,properties]
----
server.url=http://${server.host}:${server.port}/hello
server.host=my.org
server.port=9080
----

When looking up `server.url`, the property value will be resoved to `http://my.org:9080/hello`.

== Nested property expression

The property expression can be nested such as the following:

[source,properties]
----
server.url=http://${${foo}.${bar}}/hello
foo=wonder
bar=how
wonder.how=nested
----
When looking up `server.url`, the property value will be resoved to `http://nested/hello`.

On resolving the nested expression, the inner property expression must be performed first.

== Assign a default value to property expression

Sometimes, the property expression cannot be resolved due to the unexisting config property. 
Therefore, it is useful to supply a default value for the configuration expression in the format of `${a.property:value}`. The value after `:` will be the default value.

[source,properties]
----
server.url=http://${hostname:localhost}:${port:9080}/hello
----

On resolving `server.url`, since the properties `hostname` and `port` are not defined, the supplied default values will be used. 
The value of `server.url` will be `http://localhost:9080/hello`.

== Miscellaneous

A property expression might lead to infinite look by refering to itself. The implementation must detect this and report an error.
In the following example, `hostname` refers to itself and creates an indefinite loop. The implementation must be able to exit the evaluation and report an error.

[source,properties]
----
server.url=http://${hostname}:${port}/hello
hostname=${hostname}
----

Sometimes, a configuration value might contain ${...} but wants to bypass the property expansion. In order to escape the property expansion, a `\` should be used to preserve the value of `${...}`.

In the following example, the value of `server.url` will be `http://${hostname}:${port}/hello`.

[source,properties]
----
server.url=http://\${hostname}:\${port}/hello
hostname=${hostname}
----

Similarly, sometimes `:` is part of a property expression. In order to preserv `:`, `\` will also be used to preserve the `:` instead of treating it as the default value delimiter.

In the following example, the value of `server.url` will be `http://my.host:9080/hello`, as `${my\:host}` is resolved to the value of the property `my:host`.

[source,properties]
----
server.url=http://${my\:host}:9080/hello
my:host=my.host
----