= Terminology

[[application]]Application::
. An executable collection, or packaging, of one or more <<component,components>>, and zero or more
<<configuration,configurations>> that <<configure,configure>> it.

[[author]]Author::
. (verb) To create a <<configuration,configuration>> in a particular <<configuration-format,configuration format>>.
. (noun) The creator of a <<configuration,configuration>> in a particular <<configuration-format,configuration format>>.

[[component]]Component::
. A Java class, or collection of such classes, or a packaged artifact containing such classes, that, without
<<configuration,configuration>>, may be <<application,application>>- and <<environment,environment>>-independent.
. The Java source code representation of such an entity.

[[configuration]]Configuration::
. A portion, or the entirety, of a <<component,component>>'s or <<application,application>>'s state that is
<<environment,environment>>-specific.
. A persistent representation of that state, often in a human-readable <<configuration-format,configuration format>>.
. A notional, unordered set of <<configuration-entry,configuration entries>> representing the assignment of
<<configuration-value,configuration values>> for some, or all, <<configuration-key,configuration keys>> in a
<<configuration-domain,configuration domain>>.
. A kind of <<configuration-value,configuration value>>.

[[configuration-class]]Configuration Class::
. A Java class, with very specific restrictions, representing possible <<configuration,configurations>>.

[[configuration-domain]]Configuration Domain::
. The set of possible <<configuration-key,configuration keys>> for a given <<component,component>> or
<<application,application>>, regardless of the <<environment,environment>> it may find itself in, and regardless of the
<<configuration-value,configuration values>> that may be assigned to those keys in a particular
<<environment,environment>>.

[[configuration-entry]]Configuration Entry::
. A <<configuration-format,configuration-format>>-independent pairing of a <<configuration-key,configuration key>> and a
<<configuration-value,configuration value>> within a <<configuration,configuration>>.
** A configuration entry belongs to a <<configuration,configuration>> and is uniquely identified within that
<<configuration,configuration>> by its <<configuration-key,configuration key>>.

[[configuration-format]]Configuration Format::
. A particular representation of a <<configuration,configuration>>, often persistent, and often in human-readable form.
. A file format, or MIME type, or the like, designating such a representation.

[[configuration-key]]Configuration Key::
. A <<configuration-format,configuration-format>>-independent identifier that identifies one
<<configuration-entry,configuration entry>> within a <<configuration,configuration>>, and that names an associated
<<configuration-value,configuration value>>.

[[configuration-object]]Configuration Object::
. An instance of a <<configuration-class,configuration class>>.

[[configuration-value]]Configuration Value::
. A <<configuration-format,configuration-format>>-independent value of a <<configuration-entry,configuration entry>>.

[[configure]]Configure::
. To associate one or more <<configuration,configurations>> with a <<component,component>> or an
<<application,application>>, for one or more <<environment,environments>>.
. Loosely: To tailor a <<component,component>> or <<application,application>> to a given <<environment,environment>>.

[[environment]]Environment::
. A notional coordinate space in which an <<application,application>> is, or is to be, or has been, executed.

[[load]]Load::
. To acquire a <<configuration-object,configuration object>> for a <<component,component>> or
<<application,application>>.