= Terminology

This section describes the terminology used in this specification.  Many terms have several definitions depending on
context.  Links to other sections in this specification are provided.

CAUTION: You are reading an incomplete DRAFT specification.  The following is subject to change.

[[application]]Application::
. An executable collection, or packaging, of one or more <<component,components>>, and zero or more
<<configuration,configurations>> that <<configure,configure>> it for one or more <<environment,environments>>.

[[application-assembler]]Application Assembler::
. A role representing a person who packages <<component,components>> into <<application,applications>> for execution in
an <<environment,environment>>.
+
NOTE: Many times a person playing the <<component-developer,component developer>> role also plays the
<<application-assembler,application assembler>> role.

[[author]]Author::
. (verb) To create a <<configuration,configuration>> in a particular <<configuration-format,configuration format>>.
. (noun) The creator of a <<configuration,configuration>> in a particular <<configuration-format,configuration format>>.
See <<configuration-author,Configuration Author>>.

[[canonical-representation]]Canonical Representation::
. The textual form of a <<configuration-key,configuration key>> that is considered to be its authoritative,
<<configuration-format,format>>-independent, representation.  The canonical representation of a
<<configuration-key,configuration key>> is a sequence of one or more
https://www.unicode.org/charts/charindex.html[Unicode characters] in
https://www.unicode.org/reports/tr15/#Norm_Forms[Unicode's Normalization Form C (NFC)] where each character is not a
member of either the https://unicode.org/charts/nameslist/n_0000.html[C0 Controls] or
https://unicode.org/charts/nameslist/n_0080.html[C1 Controls] https://www.unicode.org/charts/nameslist/[code charts].
See the xref:logical-model.adoc[Logical Model] section.
. Any authoritative representation defined by this specification of a <<logical,logical>> entity defined by this
specification.

[[component]]Component::
. A Java class, or collection of such classes, or a packaged artifact containing such classes, that, without
<<configuration,configuration>>, may be <<application,application>>- and <<environment,environment>>-independent.
. The Java source code representation of such an entity.
+
NOTE: A component is often designed for reuse in many <<application,applications>>.

[[component-developer]]Component Developer::
. A role representing a Java developer who writes or is writing <<component,components>>.

[[configuration]]Configuration::
. A portion, or the entirety, of a <<component,component>>'s or <<application,application>>'s state that is
<<environment,environment>>-specific.
. A <<logical-model,logical model>> of such a configuration, consisting of zero or more
<<configuration-entry,configuration entries>>.  See the xref:logical-model.adoc[Logical Model] section.
. A kind of <<logical,logical>> <<configuration-value,configuration value>> within the <<logical-model,logical model>>.  See the
xref:logical-model.adoc[Logical Model] section.
. A representation of that state, often persistent, and often in a human-readable <<configuration-format,configuration
format>>.
. The act of <<configure,configuring>>.

[[configuration-author]]Configuration Author::
. The creator of a <<configuration,configuration>> represented in a particular <<configuration-format,configuration
format>>.

[[configuration-class]]Configuration Class::
. A Java class, xref:configuration-class.adoc[with very specific requirements], representing a read-only, unchanging
view of a (<<logical-model,logical>>) <<configuration,configuration>>.

[[configuration-domain]]Configuration Domain::
. The set of possible <<configuration-key,configuration keys>> for a given <<component,component>> or
<<application,application>>, regardless of the <<environment,environment>> it may find itself in, and regardless of the
<<configuration-value,configuration values>> that may be assigned to those keys in a particular
<<environment,environment>>.

[[configuration-entry]]Configuration Entry::
. A <<configuration-format,configuration-format>>-independent pairing of a <<configuration-key,configuration key>> and a
<<configuration-value,configuration value>> within a <<configuration,configuration>>.  See the
xref:logical-model.adoc[Logical Model] section.
+
NOTE: A configuration entry belongs to a <<configuration,configuration>> and is uniquely identified within that
<<configuration,configuration>> by its <<configuration-key,configuration key>>.

[[configuration-format]]Configuration Format::
. A particular representation of a <<configuration,configuration>>, often persistent, and often in human-readable form.
. A file format, or MIME type, or the like, designating such a representation.

[[configuration-key]]Configuration Key::
. A <<configuration-format,configuration-format>>-independent identifier that identifies one
<<configuration-entry,configuration entry>> within a <<configuration,configuration>>, and that names an associated
<<configuration-value,configuration value>>.  See the xref:logical-model.adoc[Logical Model] section.

[[configuration-object]]Configuration Object::
. An instance of a <<configuration-class,configuration class>>.

[[configuration-path]]Configuration Path::
. A <<logical,logical>> sequence of <<configuration-key,configuration keys>> that identifies a <<configuration-value,configuration
value>> within a (possibly nested) <<configuration,configuration>>.  See the xref:logical-model.adoc[Logical Model] section.

[[configuration-path-separator]]Configuration Path Separator::
. A <<logical,logical>> token that separates <<configuration-key,configuration keys>> from one another in a
<<configuration-path,configuration path>>.  See the xref:logical-model.adoc[Logical Model] section.
. A particular <<configuration-format,configuration format's>> representation of such a token.

[[configuration-value]]Configuration Value::
. A <<configuration-format,configuration-format>>-independent value of a <<configuration-entry,configuration entry>>.
See the xref:logical-model.adoc[Logical Model] section.
+
NOTE: A configuration value may be a <<configuration,configuration>>.

[[configure]]Configure::
. To associate one or more <<configuration,configurations>> with a <<component,component>> or an
<<application,application>>, for one or more <<environment,environments>>.
. Loosely: To tailor a <<component,component>> or <<application,application>> to a given <<environment,environment>>.

[[environment]]Environment::
. A notional coordinate space in which an <<application,application>> is, or is to be, or has been, executed.

[[load]]Load::
. To acquire a <<configuration-object,configuration object>> for a <<component,component>> or
<<application,application>>.

[[logical]]Logical::
. Divorced from programming model, programming language, format, and representational concerns.

[[logical-model]]Logical Model::
. The model of configuration used by this specification that is independent of programming construct and <<configuration-format,configuration format>> concerns.
. The xref:logical-model.adoc[section within this specification describing this model].

[[nested-configuration]]Nested Configuration::
. In the <<logical-model,logical model>>, a <<configuration,configuration>> that is a
<<configuration-value,configuration value>> appearing in a <<configuration-entry,configuration entry>>.  See the
xref:logical-model.adoc[Logical Model] section.

[[raw-configuration-value]]Raw Configuration Value::
. A <<configuration-value,configuration value>> that is not itself a <<configuration,configuration>>.  See the
xref:logical-model.adoc[Logical Model] section.

[[raw-value]]Raw Value:: See <<Raw Configuration Value>>.
