= Terminology

This section describes the terminology used in this specification.  Many terms have several definitions depending on
context.  Links to other sections in this specification are provided.

CAUTION: You are reading an incomplete DRAFT specification.  The following is subject to change.

[[absence]]Absence::
. The property of any value that describes its non-existence.
+
NOTE: Contrast absence with <<presence,presence>>.
+
NOTE: In Java, and in this specification, absence is often represented by `null`.

[[application]]Application::
. An executable collection, or packaging, of one or more <<component,components>>, and zero or more
<<configuration,configurations>> that <<configure,configure>> it for one or more <<environment,environments>>.

[[application-assembler]]Application Assembler::
. A role representing a person who packages <<component,components>> into <<application,applications>> for deployment
and/or execution in an <<environment,environment>>.
. A member of the Jakarta EE Platform's
https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0.html#application-assembler[Application
Assembler] role set.
+
NOTE: Many times a person playing the <<component-developer,component developer>> role also plays the
<<application-assembler,application assembler>> role.

[[author]]Author::
. (verb) To create a <<configuration,configuration>> in a particular <<configuration-format,configuration format>>.
. (noun) The creator of a <<configuration,configuration>> in a particular <<configuration-format,configuration format>>.
See <<configuration-author,Configuration Author>>.

[[canonical-representation]]Canonical Representation::
. The textual form of a <<configuration-key,configuration key>> that is considered to be its authoritative,
<<configuration-format,format>>-independent, representation.  The canonical representation of a
<<configuration-key,configuration key>> is a sequence of one or more
https://www.unicode.org/charts/charindex.html[Unicode characters] in
https://www.unicode.org/reports/tr15/#Norm_Forms[Unicode's Normalization Form C (NFC)] where each character is not a
member of either the https://unicode.org/charts/nameslist/n_0000.html[C0 Controls] or
https://unicode.org/charts/nameslist/n_0080.html[C1 Controls] https://www.unicode.org/charts/nameslist/[code charts].
See the xref:logical-model.adoc[Logical Model] section.
. Any authoritative representation defined by this specification of a <<logical,logical>> entity defined by this
specification.

[[component]]Component::
. A Java class, or collection of such classes, or a packaged artifact containing such classes, that, without
<<configuration,configuration>>, may be <<application,application>>- and <<environment,environment>>-independent.
. The Java source code representation of such an entity.
+
NOTE: A component is often designed for reuse in many <<application,applications>>.

[[component-developer]]Component Developer::
. A role representing a Java developer who writes or is writing <<component,components>>.
. A member of the Jakarta EE Platform's
https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0.html#application-component-provider[Application
Component Provider] role set.

[[configuration]]Configuration::
. A portion, or the entirety, of a <<component,component>>'s or <<application,application>>'s state that is
<<environment,environment>>-specific.
. A <<logical-model,logical model>> of such a configuration, consisting of zero or more
<<configuration-entry,configuration entries>>.  See the xref:logical-model.adoc[Logical Model] section.
. A kind of <<logical,logical>> <<configuration-value,configuration value>> within the <<logical-model,logical model>>.  See the
xref:logical-model.adoc[Logical Model] section.
. A representation of that state, often persistent, and often in a human-readable <<configuration-format,configuration
format>>.
. The act of <<configure,configuring>>.

[[configuration-author]]Configuration Author::
. The creator of a <<configuration,configuration>> represented in a particular <<configuration-format,configuration
format>>.

[[configuration-class]]Configuration Class::
. A Java class, xref:configuration-class.adoc[with very specific requirements], representing a read-only, unchanging
collection of <<configuration-path,configuration paths>> and Java types representing the kinds of
<<configuration-value,configuration values>> they may identify.
. The xref:configuration-class.adoc[section within this specfication describing this concept]

[[configuration-domain]]Configuration Domain::
. The set of possible <<configuration-key,configuration keys>> for a given <<component,component>> or
<<application,application>>, regardless of the <<environment,environment>> it may find itself in, and regardless of the
<<configuration-value,configuration values>> that may be assigned to those keys in a particular
<<environment,environment>>.
+
// TODO: This needs to be cleaned up

[[configuration-entry]]Configuration Entry::
. A <<configuration-format,configuration-format>>-independent pairing of a <<configuration-key,configuration key>> and a
<<configuration-value,configuration value>> within a <<configuration,configuration>>.  See the
xref:logical-model.adoc[Logical Model] section.
+
NOTE: A configuration entry belongs to a <<configuration,configuration>> and is uniquely identified within that
<<configuration,configuration>> by its <<configuration-key,configuration key>>.

[[configuration-format]]Configuration Format::
. A particular representation kind for <<configuration,configurations>>, often persistent, and often in human-readable form.
. A file format, media type, MIME type, or the like, designating such a representation.

[[configuration-key]]Configuration Key::
. A <<configuration-format,configuration-format>>-independent identifier that identifies one
<<configuration-entry,configuration entry>> within a <<configuration,configuration>>, and that names an associated
<<configuration-value,configuration value>>.  See the xref:logical-model.adoc[Logical Model] section.

[[configuration-object]]Configuration Object::
. An instance of a <<configuration-class,configuration class>>, especially as supplied by an implementation of the
`jakarta.config.Loader` interface.
+
NOTE: Configuration objects may be <<absence,absent>> or <<presence,present>>.

[[configuration-path]]Configuration Path::
. A <<logical,logical>> sequence of <<configuration-key,configuration keys>> that identifies a <<configuration-value,configuration
value>> within a (possibly nested) <<configuration,configuration>>.  See the xref:logical-model.adoc[Logical Model] section.

[[configuration-path-separator]]Configuration Path Separator::
. A <<logical,logical>> token that separates <<configuration-key,configuration keys>> from one another in a
<<configuration-path,configuration path>>.  See the xref:logical-model.adoc[Logical Model] section.
. A particular <<configuration-format,configuration format's>> representation of such a token.

[[configuration-value]]Configuration Value::
. A <<configuration-format,configuration-format>>-independent value of a <<configuration-entry,configuration entry>>.
See the xref:logical-model.adoc[Logical Model] section.
+
NOTE: A configuration value may be a <<configuration,configuration>>.

[[configure]]Configure::
. To associate one or more <<configuration,configurations>> with a <<component,component>> or an
<<application,application>>, for one or more <<environment,environments>>.
. Loosely: To tailor a <<component,component>> or <<application,application>> to a given <<environment,environment>>.

[[environment]]Environment::
. A <<logical,logical>> coordinate space in which an <<application,application>> is, or is to be, or has been, executed.

[[implementor]]Implementor::
. A role representing one who implements this specification.
. A member of the https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0.html#a162[Jakarta EE Product
Provider] role set.

[[immutable]]Immutable::
. Both <<unmodifiable,unmodifiable>> and <<unchanging,unchanging>>.

[[load]]Load::
. To acquire a <<configuration-object,configuration object>> for a <<component,component>> or
<<application,application>>.

[[load-request]]Load Request::
. The Java objects necessary to <<load,load>> a <<configuration-object,configuration object>>.  See the
xref:loading.adoc[Loading] section.

[[logical]]Logical::
. Divorced from programming model, programming language, format, and representational concerns.

[[logical-model]]Logical Model::
. The model of configuration used by this specification that is independent of programming construct and <<configuration-format,configuration format>> concerns.
. The xref:logical-model.adoc[section within this specification describing this model].

[[nested-configuration]]Nested Configuration::
. In the <<logical-model,logical model>>, a <<configuration,configuration>> that is a
<<configuration-value,configuration value>> appearing in a <<configuration-entry,configuration entry>>.  See the
xref:logical-model.adoc[Logical Model] section.

[[presence]]Presence::
. The property of any value that describes its existence.
+
NOTE: Contrast presence with <<absence,absence>>.

[[raw-configuration-value]]Raw Configuration Value::
. A <<configuration-value,configuration value>> that is not itself a <<configuration,configuration>>.  See the
xref:logical-model.adoc[Logical Model] section.

[[raw-value]]Raw Value:: See <<Raw Configuration Value>>.

[[resolved-configuration-path]]Resolved Configuration Path::
. A <<configuration-path,configuration path>> that identifies a <<presence,present>> <<configuration-value,configuration
value>>.  See <<unresolved-configuration-path,Unresolved Configuration Path>>.
+
NOTE: Whether the <<presence,presence>> is transient or permanent is not specified.

[[suitability]]Suitability::
. The property describing a <<configuration-object,configuration object>>'s fitness for a particular <<load-request,load
request>>.  <<configuration-object,Configuration objects>> may be more or less _suitable_ for a given
<<load-request,load request>>.

[[unchanging]]Unchanging::
. Never internally changing; stable.  See <<unmodifiable,Unmodifiable>> and <<immutable,Immutable>>.
+
NOTE: An unchanging entity may not be <<unmodifiable,unmodifiable>> and so may not be <<immutable,immutable>>.

[[unmodifiable]]Unmodifiable::
. Incapable of being altered through publicly accessible means. See <<immutable,Immutable>> and
<<unchanging,Unchanging>>.
+
NOTE: An unmodifiable entity may not be <<unchanging,unchanging>> and so may not be <<immutable,immutable>>.

[[unresolved-configuration-path]]Unresolved Configuration Path::
. A <<configuration-path,configuration path>> that identifies an <<absence,absent>> <<configuration-value,configuration
value>>.  See <<resolved-configuration-path,Resolved Configuration Path>>.
+
NOTE: Whether the <<absence,absence>> is transient or permanent is not specified.